### ISSUE TITLE
update time-series map code to match otl-racial-change

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-home-value#10]
@ilyankou - Please make these updates and bill me. This should be relatively easy because you can use code that you recently created for https://github.com/ontheline/otl-racial-change

- [x] Currently, the arrow keys advance the years, but also slide the map across the screen. Please fix to match otl-racial-change

- [x] Display CartoDB map labels and non-label layers, as you did in otl-racial-change

- [x] Remove the star on Hartford, since it's not necessarily with labels above.

**Comment by ilyankou** [comment]
@JackDougherty In the title, I changed `< >` to arrows (`&larr; or &larr;`). But if you prefer your way, change `<` to `lt;` and `>` to `&gt;`. It is not recommended having opening/closing tags in plaintext in html.

**Comment by JackDougherty** [comment]
perfect -- thanks!
